### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by mogadanez** [airjp73/remix-validated-form#363]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: ^5.1.5
- `@remix-validated-form/with-zod`: ^2.0.7

### Please provide a link to a minimal reproduction of the issue.

--

### Steps to Reproduce the Bug or Issue

If open form via client side -  it opens fine, but if refresh page -  got error:

TypeError: Cannot read properties of null (reading 'useState')
    at useState (/project/node_modules/remix-validated-form/node_modules/react/cjs/react.development.js:1622:21)
    at useFormId (/project/node_modules/remix-validated-form/dist/index.cjs.js:1536:50)
    at ValidatedForm (/project/node_modules/remix-validated-form/dist/index.cjs.js:1590:18)
    at renderWithHooks (/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:9488:16)

### Expected behavior

Should refresh nornaly

### Platform

- OS: macOS
- Browser: Chrome
- Version: 123

**Comment by mogadanez** [comment]
Found Issue myself. 

I Switched  remix app to canary,  and this was cause  of error.  
Adding resolution to package.json  works as fix.

**Comment by yarapolana** [comment]
@mogadanez can you share what you added?
I am experiencing the same error though I am not using remix canary I am using 2.8.1
