### ISSUE TITLE
[Bug]: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gederer** [airjp73/remix-validated-form#93]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

"remix-validated-form": "^4.3.0"
"@remix-validated-form/with-zod": "^2.0.1"

### Please provide a link to a minimal reproduction of the issue.

https://github.com/gederer/form-stuff

### Steps to Reproduce the Bug or Issue

1. Create a new Remix Indie stack project w/ `npx create-remix --template remix-run/indie-stack`
2. Follow the "Install" and "Integrating your components" docs for remix-validated-form
3. `npm run dev`
4. Visit the route of the `ValidatedForm` created in step 2, above

### Expected behavior

The page containing the `ValidatedForm` should render. Instead, an error error message along with a stacktrace is displayed.

```
/Users/username/dev/experiments/form-stuff/node_modules/remix-validated-form/src/ValidatedForm.tsx:1
import { Form as RemixForm, useFetcher, useSubmit } from "@remix-run/react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .tsx] (/Users/gregederer/dev/experiments/form-stuff/node_modules/ts-node/src/index.ts:1445:43)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/gregederer/dev/experiments/form-stuff/app/routes/new-note.tsx:1:31)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### Platform

- OS: macOs Monterey
- Browser: Chrome
- Version: 100.0.4896.75 (Official Build) (x86_64)

**Comment by gederer** [comment]
My IDE (Webstorm) auto-imported `import { ValidatedForm } from "remix-validated-form/src/ValidatedForm";`. Oops! Fixed it. Works fine now.
